// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxcJV8lyxAMuJI5107LustsHjmKHXD8Q',
    appId: '1:189863131384:web:5416b351e450b16abce30d',
    messagingSenderId: '189863131384',
    projectId: 'filema-57c3b',
    authDomain: 'filema-57c3b.firebaseapp.com',
    storageBucket: 'filema-57c3b.firebasestorage.app',
    measurementId: 'G-KJ7T24LMEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZv8wKMWEyqmAHUjiVu58HDHZAnES1DBo',
    appId: '1:189863131384:android:fc39340a699dbc36bce30d',
    messagingSenderId: '189863131384',
    projectId: 'filema-57c3b',
    storageBucket: 'filema-57c3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTAknlx98X1lNGH40Dl18vluXXuJmMzQ',
    appId: '1:189863131384:ios:5bac7c78d143d88dbce30d',
    messagingSenderId: '189863131384',
    projectId: 'filema-57c3b',
    storageBucket: 'filema-57c3b.firebasestorage.app',
    iosBundleId: 'com.example.filema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrTAknlx98X1lNGH40Dl18vluXXuJmMzQ',
    appId: '1:189863131384:ios:5bac7c78d143d88dbce30d',
    messagingSenderId: '189863131384',
    projectId: 'filema-57c3b',
    storageBucket: 'filema-57c3b.firebasestorage.app',
    iosBundleId: 'com.example.filema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxcJV8lyxAMuJI5107LustsHjmKHXD8Q',
    appId: '1:189863131384:web:3e96f1c002c7b374bce30d',
    messagingSenderId: '189863131384',
    projectId: 'filema-57c3b',
    authDomain: 'filema-57c3b.firebaseapp.com',
    storageBucket: 'filema-57c3b.firebasestorage.app',
    measurementId: 'G-LH4H5GBL2F',
  );
}
